all:
  vars:
    ansible_connection: ssh
    ansible_user: jincy
    ansible_password: jincytsl
    ansible_sudo_pass: jincytsl
    ansible_become: true
    kafka_broker_service_environment_overrides:
      KAFKA_HEAP_OPTS: "-Xmx1g"
    ssl_enabled: true
    ssl_mutual_auth_enabled: true
    kafka_broker_rest_proxy_enabled: false

zookeeper:
  hosts:
    ubuntu:

kafka_broker:
  hosts:
    ubuntu:

ksql:
  hosts:
    ubuntu:

control_center:
  hosts:
    ubuntu:        


